// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJCrGIl5OH7Cy0Vwadx8xfIunEdfGC2bo',
    appId: '1:332437526658:web:d9ac324ed49dd00a00bc9b',
    messagingSenderId: '332437526658',
    projectId: 'inclass12v',
    authDomain: 'inclass12v.firebaseapp.com',
    storageBucket: 'inclass12v.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC24n1IFUwtuiiKL144rtdV38osfXfpcuI',
    appId: '1:332437526658:android:9b550145105f09f300bc9b',
    messagingSenderId: '332437526658',
    projectId: 'inclass12v',
    storageBucket: 'inclass12v.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0Ibuw6OEVyaV0wqxLkjqUP5X_VIY6NQM',
    appId: '1:332437526658:ios:a2a87a73c3df5bf300bc9b',
    messagingSenderId: '332437526658',
    projectId: 'inclass12v',
    storageBucket: 'inclass12v.firebasestorage.app',
    iosBundleId: 'com.example.inclass12',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0Ibuw6OEVyaV0wqxLkjqUP5X_VIY6NQM',
    appId: '1:332437526658:ios:a2a87a73c3df5bf300bc9b',
    messagingSenderId: '332437526658',
    projectId: 'inclass12v',
    storageBucket: 'inclass12v.firebasestorage.app',
    iosBundleId: 'com.example.inclass12',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJCrGIl5OH7Cy0Vwadx8xfIunEdfGC2bo',
    appId: '1:332437526658:web:9bf56e0b55a53be300bc9b',
    messagingSenderId: '332437526658',
    projectId: 'inclass12v',
    authDomain: 'inclass12v.firebaseapp.com',
    storageBucket: 'inclass12v.firebasestorage.app',
  );
}
